# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  encoding: utf8
  pool: <%= ENV['DB_POOL_SIZE'] %>
  wait_timeout: <%= ENV['DB_WAIT_TIMEOUT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_DATABASE'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  reconnect: true
  <% if ENV['DB_REPLICA_HOST'] %>
  adapter: 'mysql2_makara'
  makara:
    id: mysql
    blacklist_duration: 0
    sticky: true
    connections:
      - role: master
        host: <%= ENV['DB_HOST'] %>
        name: primary
      - role: slave
        host: <%= ENV['DB_REPLICA_HOST'] %>
        name: replica
  <% else %>
  adapter: mysql2
  <% end %>

development:
  <<: *default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default

# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
staging:
  <<: *default

production:
  <<: *default

docker_development:
  <<: *default

raspberry_pi:
  <<: *default
