default: &default
  access_token_age: <%= 60.days %>
  refresh_token_age: <%= 1.years %>

development:
  <<: *default

test:
  <<: *default
  access_token_age: <%= 2.seconds %>
  refresh_token_age: <%= 6.seconds %>

staging:
  <<: *default

production:
  <<: *default

docker_development:
  <<: *default

raspberry_pi:
  <<: *default
